architecture:
  encoder_channels: [8, 16, 32]
  bottleneck_channels: 52
  kernel_size: 3
  normalization: "batch_norm"
  group_norm_num_groups: 8
  activation: h_swish
  upsampling_mode: nearest_neighbor
  use_residual_connections: false
  use_attention_gates: false
  dropout_probability: 0.0
  input_channels: 3
  use_depthwise_separable_convolutions: false
  use_single_convolution_per_block: false
  skip_connection_mode: concat

training:
  use_cyclic_learning_rate: false
  cyclic_learning_rate_minimum: 1e-6
  cyclic_learning_rate_maximum: 1e-3
  cyclic_learning_rate_half_cycle_epochs: 2
  data_root: data/Wbc
  learning_rate: 0.001
  weight_decay: 1e-4
  batch_size: 64
  epochs: 100
  dataset: Wbc
  image_size: 256
  # max_samples: 20000
  use_color_input: true
  early_stopping_patience: 10
  early_stopping_minimum_improvement_delta: 0.001
  hypothesis: "No hypothesis -  Reproduce check run 2."
  notes: "baseline, [8,16,32]/52, standard conv, ~96.5K params"